import React from 'react'
import { Navigate } from 'react-router'; 
import { useGlobalContext } from '../Context/AuthContextProvider';
const ProtectedRouteComp = ({children}) => {
    //we will allow the user to access or see the UI generated by users page or children page of protectedroutercomp if only the user who are authenticated.`
  const {isAuth} = useGlobalContext(); 
   if(isAuth){
    return (
        <Navigate to="/login"></Navigate>
      )
   }
 return children //  this is else part in this children we have <users></users> components
 
}

export default ProtectedRouteComp
